# Training Config
as_test: False
seed: 42

lr: 0.0001
num_epochs: 2
batch_size: 32
gradient_accumulation_steps: 1
mixed_precision: 'no'

# TODO: model config

# Dataset Config
dataset:
  _target_: train.get_dataset

# DeepSpeed Config
use_deepseed: False
deepspeed_config: "deepspeed/ds_config_zero0.json"

# Ray Config (TorchTrainer)
scaling_config:
  _target_: ray.train.ScalingConfig
  num_workers: 1
  use_gpu: True
  resources_per_worker:
    CPU: 4
    GPU: 1

run_config:
  _target_: ray.train.RunConfig
  storage_path: 
    _target_: os.path.abspath
    path: 'checkpoints'
  checkpoint_config:
    _target_: ray.train.CheckpointConfig
    num_to_keep: 2
    checkpoint_score_attribute: "accuracy"
    checkpoint_score_order: "max"

data_config:
  _target_: ray.train.DataConfig
  _convert_: all
  datasets_to_split: "all"
